### ISSUE TITLE
Link format

### ISSUE THREAD

**Issue by FunsKiTo** [Official-Husko/mul-tor#27]
When setting the 'link-format' in the presets settings, I use:
`"link-format": "{file_url}"`
to get in the .txt:
`2024-04-12 20:52:57.665009 | GoFile | filename.rar - https://gofile.io/d/asdgew`

Would be nice to have a formatting option to only get:
`filename.rar - https://gofile.io/d/asdgew`

**Comment by Official-Husko** [comment]
did you check the the file called "file_links_formatted"? Normally it should have the special format links in there.

**Comment by FunsKiTo** [comment]
> did you check the the file called "file_links_formatted.txt"? Normally it should have the special format links in there.

Yes, that's the file I am referring to.

**Comment by Official-Husko** [comment]
Alright the link format is now fully customizable. Refer to the [wiki page](https://github.com/Official-Husko/mul-tor/wiki/Preset-Configuration#link-format) for all available options. Available in v1.5.1

fixed in commit [dc916ec](https://github.com/Official-Husko/mul-tor/commit/dc916ec930a5285d89c21f421b83f26d203f7878)

**Comment by Official-Husko** [comment]
Fix available in release [v1.5.1](https://github.com/Official-Husko/mul-tor/releases/tag/1.5.1)
